import { describe, expect, it } from "vitest";

import { LiteCompatError } from "../src/error";
import {
    Skeleton,
    Bone,
    ReflectionProbe,
    Layer,
    EffectLayer,
    DepthRenderer,
    GeometryBufferRenderer,
    BoundingBoxRenderer,
    PostProcess,
    BlackAndWhitePostProcess,
    BlurPostProcess,
    BloomEffect,
    ChromaticAberrationPostProcess,
    DepthOfFieldEffect,
    DefaultRenderingPipeline,
    FxaaPostProcess,
    SSAO2RenderingPipeline,
    ParticleHelper,
    ParticleSystemSet,
    PointsCloudSystem,
    HavokPlugin,
    PhysicsAggregate,
    PhysicsBody,
    PhysicsShape,
    CannonJSPlugin,
    AmmoJSPlugin,
    RecastJSPlugin,
    AudioEngine,
    WeightedSound,
    OBJFileLoader,
    STLFileLoader,
    FBXFileLoader,
    BVHFileLoader,
    SpriteMap,
    SpritePackedManager,
    VirtualJoystick,
    SceneOptimizer,
} from "../src/unsupported/unsupported-extended";

describe("Extended unsupported stubs throw on construction", () => {
    const cases: Array<[string, () => unknown]> = [
        ["Skeleton", () => new Skeleton()],
        ["Bone", () => new Bone()],
        ["ReflectionProbe", () => new ReflectionProbe()],
        ["Layer", () => new Layer()],
        ["EffectLayer", () => new EffectLayer()],
        ["DepthRenderer", () => new DepthRenderer()],
        ["GeometryBufferRenderer", () => new GeometryBufferRenderer()],
        ["BoundingBoxRenderer", () => new BoundingBoxRenderer()],
        ["PostProcess", () => new PostProcess()],
        ["BlackAndWhitePostProcess", () => new BlackAndWhitePostProcess()],
        ["BlurPostProcess", () => new BlurPostProcess()],
        ["BloomEffect", () => new BloomEffect()],
        ["ChromaticAberrationPostProcess", () => new ChromaticAberrationPostProcess()],
        ["DepthOfFieldEffect", () => new DepthOfFieldEffect()],
        ["DefaultRenderingPipeline", () => new DefaultRenderingPipeline()],
        ["FxaaPostProcess", () => new FxaaPostProcess()],
        ["SSAO2RenderingPipeline", () => new SSAO2RenderingPipeline()],
        ["ParticleHelper", () => new ParticleHelper()],
        ["ParticleSystemSet", () => new ParticleSystemSet()],
        ["PointsCloudSystem", () => new PointsCloudSystem()],
        ["HavokPlugin", () => new HavokPlugin()],
        ["PhysicsAggregate", () => new PhysicsAggregate()],
        ["PhysicsBody", () => new PhysicsBody()],
        ["PhysicsShape", () => new PhysicsShape()],
        ["CannonJSPlugin", () => new CannonJSPlugin()],
        ["AmmoJSPlugin", () => new AmmoJSPlugin()],
        ["RecastJSPlugin", () => new RecastJSPlugin()],
        ["AudioEngine", () => new AudioEngine()],
        ["WeightedSound", () => new WeightedSound()],
        ["OBJFileLoader", () => new OBJFileLoader()],
        ["STLFileLoader", () => new STLFileLoader()],
        ["FBXFileLoader", () => new FBXFileLoader()],
        ["BVHFileLoader", () => new BVHFileLoader()],
        ["SpriteMap", () => new SpriteMap()],
        ["SpritePackedManager", () => new SpritePackedManager()],
        ["VirtualJoystick", () => new VirtualJoystick()],
        ["SceneOptimizer", () => new SceneOptimizer()],
    ];

    it.each(cases)("%s throws LiteCompatError naming the API", (name, construct) => {
        expect(construct).toThrow(LiteCompatError);
        expect(construct).toThrow(new RegExp(name));
    });
});
