/** Scene 61 — NME normal-as-color.
 *
 *  Adds a vertex→fragment varying + fragment-side math to the minimal graph
 *  from scene 60. The normal attribute is read in the vertex stage and carried
 *  across via an auto-generated varying; the fragment stage remaps it
 *  `normal * 0.5 + 0.5` so each cardinal direction shows a distinct channel.
 *
 *  Graph:
 *    Vertex:   position ──► TransformBlock(× worldViewProjection) ──► VertexOutput
 *    Fragment: normal   ──► ScaleBlock(factor=0.5) ─┐
 *              bias(vec3 uniform 0.5)              ─► AddBlock ──► FragmentOutput.rgb
 *              alpha(float uniform 1.0) ────────────────────────► FragmentOutput.a
 *
 *  Both BJS and Lite parse the SAME JSON so parity holds bit-wise.
 */
export const SCENE61_NME_JSON = {
    tags: null,
    ignoreAlpha: false,
    maxSimultaneousLights: 4,
    mode: 0,
    forceAlphaBlending: false,
    id: "scene61nm",
    name: "Scene61NME",
    customType: "BABYLON.NodeMaterial",
    checkReadyOnEveryCall: false,
    checkReadyOnlyOnce: false,
    state: "",
    alpha: 1,
    backFaceCulling: true,
    sideOrientation: 1,
    alphaMode: 2,
    _needAlphaBlending: false,
    _needAlphaTesting: false,
    forceDepthWrite: false,
    separateCullingPass: false,
    fogEnabled: true,
    pointSize: 1,
    zOffset: 0,
    zOffsetUnits: 0,
    pointsCloud: false,
    fillMode: 0,
    editorData: null,
    customBlocks: [],
    blocks: [
        // id=1 position attribute (vec3)
        {
            customType: "BABYLON.InputBlock",
            id: 1,
            name: "position",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 8,
            mode: 1,
            systemValue: null,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
        },
        // id=2 worldViewProjection system value (mat4)
        {
            customType: "BABYLON.InputBlock",
            id: 2,
            name: "worldViewProjection",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 128,
            mode: 0,
            systemValue: 6,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
        },
        // id=3 TransformBlock: position × WVP
        {
            customType: "BABYLON.TransformBlock",
            id: 3,
            name: "Transform",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [
                { name: "vector", inputName: "vector", displayName: "vector", targetBlockId: 1, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
                { name: "transform", inputName: "transform", displayName: "transform", targetBlockId: 2, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
            ],
            outputs: [{ name: "output" }, { name: "xyz" }],
            complementZ: 0,
            complementW: 1,
        },
        // id=4 VertexOutput
        {
            customType: "BABYLON.VertexOutputBlock",
            id: 4,
            name: "VertexOutput",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [{ name: "vector", inputName: "vector", displayName: "vector", targetBlockId: 3, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 }],
            outputs: [],
        },
        // id=5 normal attribute (vec3) — read in vertex, bridged to fragment via varying
        {
            customType: "BABYLON.InputBlock",
            id: 5,
            name: "normal",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 8,
            mode: 1,
            systemValue: null,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
        },
        // id=6 halfScale uniform (float = 0.5)
        {
            customType: "BABYLON.InputBlock",
            id: 6,
            name: "halfScale",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 2,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 1,
            mode: 0,
            systemValue: null,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
            valueType: "number",
            value: 0.5,
        },
        // id=7 ScaleBlock (normal * 0.5)
        {
            customType: "BABYLON.ScaleBlock",
            id: 7,
            name: "Scale",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 4,
            inputs: [
                { name: "input", inputName: "input", displayName: "input", targetBlockId: 5, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
                { name: "factor", inputName: "factor", displayName: "factor", targetBlockId: 6, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
            ],
            outputs: [{ name: "output" }],
        },
        // id=8 bias uniform (vec3 = (0.5, 0.5, 0.5))
        {
            customType: "BABYLON.InputBlock",
            id: 8,
            name: "bias",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 2,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 8,
            mode: 0,
            systemValue: null,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
            valueType: "BABYLON.Vector3",
            value: [0.5, 0.5, 0.5],
        },
        // id=9 AddBlock (scaled normal + bias)
        {
            customType: "BABYLON.AddBlock",
            id: 9,
            name: "Add",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 4,
            inputs: [
                { name: "left", inputName: "left", displayName: "left", targetBlockId: 7, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
                { name: "right", inputName: "right", displayName: "right", targetBlockId: 8, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
            ],
            outputs: [{ name: "output" }],
        },
        // id=10 alpha uniform (float = 1.0)
        {
            customType: "BABYLON.InputBlock",
            id: 10,
            name: "alpha",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 2,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 1,
            mode: 0,
            systemValue: null,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
            valueType: "number",
            value: 1,
        },
        // id=11 FragmentOutput (rgb = add.output, a = alpha)
        {
            customType: "BABYLON.FragmentOutputBlock",
            id: 11,
            name: "FragmentOutput",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 2,
            inputs: [
                { name: "rgba", inputName: "rgba", displayName: "rgba", isExposedOnFrame: true, exposedPortPosition: -1 },
                { name: "rgb", inputName: "rgb", displayName: "rgb", targetBlockId: 9, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
                { name: "a", inputName: "a", displayName: "a", targetBlockId: 10, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
            ],
            outputs: [],
            convertToGammaSpace: false,
            convertToLinearSpace: false,
            useLogarithmicDepth: false,
        },
    ],
    outputNodes: [4, 11],
};
