/** Scene 60 — NME minimal (flat colour).
 *
 *  Smallest possible Node Material: InputBlock(color, uniform, vec4) feeds a
 *  FragmentOutputBlock. Vertex path is the canonical WVP × position through a
 *  TransformBlock. Both BJS and Lite parse the SAME inline JSON so parity holds.
 */
export const SCENE60_NME_JSON = {
    tags: null,
    ignoreAlpha: false,
    maxSimultaneousLights: 4,
    mode: 0,
    forceAlphaBlending: false,
    id: "scene60nm",
    name: "Scene60NME",
    customType: "BABYLON.NodeMaterial",
    checkReadyOnEveryCall: false,
    checkReadyOnlyOnce: false,
    state: "",
    alpha: 1,
    backFaceCulling: true,
    sideOrientation: 1,
    alphaMode: 2,
    _needAlphaBlending: false,
    _needAlphaTesting: false,
    forceDepthWrite: false,
    separateCullingPass: false,
    fogEnabled: true,
    pointSize: 1,
    zOffset: 0,
    zOffsetUnits: 0,
    pointsCloud: false,
    fillMode: 0,
    editorData: null,
    customBlocks: [],
    blocks: [
        {
            customType: "BABYLON.InputBlock",
            id: 1,
            name: "position",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 8,
            mode: 1,
            systemValue: null,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
        },
        {
            customType: "BABYLON.InputBlock",
            id: 2,
            name: "worldViewProjection",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 128,
            mode: 0,
            systemValue: 6,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
        },
        {
            customType: "BABYLON.TransformBlock",
            id: 3,
            name: "Transform",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [
                { name: "vector", inputName: "vector", displayName: "vector", targetBlockId: 1, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
                { name: "transform", inputName: "transform", displayName: "transform", targetBlockId: 2, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
            ],
            outputs: [{ name: "output" }, { name: "xyz" }],
            complementZ: 0,
            complementW: 1,
        },
        {
            customType: "BABYLON.VertexOutputBlock",
            id: 4,
            name: "VertexOutput",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 1,
            inputs: [{ name: "vector", inputName: "vector", displayName: "vector", targetBlockId: 3, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 }],
            outputs: [],
        },
        {
            customType: "BABYLON.InputBlock",
            id: 5,
            name: "color",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 2,
            inputs: [],
            outputs: [{ name: "output" }],
            type: 64,
            mode: 0,
            systemValue: null,
            animationType: 0,
            min: 0,
            max: 0,
            isBoolean: false,
            matrixMode: 0,
            isConstant: false,
            groupInInspector: "",
            convertToGammaSpace: false,
            convertToLinearSpace: false,
            valueType: "BABYLON.Color4",
            value: [0.85, 0.2, 0.2, 1],
        },
        {
            customType: "BABYLON.FragmentOutputBlock",
            id: 6,
            name: "FragmentOutput",
            comments: "",
            visibleInInspector: false,
            visibleOnFrame: false,
            target: 2,
            inputs: [
                { name: "rgba", inputName: "rgba", displayName: "rgba", targetBlockId: 5, targetConnectionName: "output", isExposedOnFrame: true, exposedPortPosition: -1 },
                { name: "rgb", inputName: "rgb", displayName: "rgb", isExposedOnFrame: true, exposedPortPosition: -1 },
                { name: "a", inputName: "a", displayName: "a", isExposedOnFrame: true, exposedPortPosition: -1 },
            ],
            outputs: [],
            convertToGammaSpace: false,
            convertToLinearSpace: false,
            useLogarithmicDepth: false,
        },
    ],
    outputNodes: [4, 6],
};
