/**
 * GPU mipmap generation via render-pass blit.
 * WebGPU has no built-in generateMipmaps() — we render a fullscreen triangle
 * from mip N-1 → mip N for each level. For sRGB textures, the GPU automatically
 * converts sRGB→linear on read and linear→sRGB on write, so filtering is correct.
 */

import { getOrCreateSampler } from "../resource/gpu-pool.js";

const BLIT_SHADER = /* wgsl */ `
@group(0) @binding(0) var srcTexture: texture_2d<f32>;
@group(0) @binding(1) var srcSampler: sampler;

struct VertexOutput {
  @builtin(position) position: vec4<f32>,
  @location(0) uv: vec2<f32>,
};

@vertex
fn vs(@builtin(vertex_index) vi: u32) -> VertexOutput {
  // Fullscreen triangle covering the viewport
  var pos = array<vec2<f32>, 3>(
    vec2<f32>(-1.0, -1.0),
    vec2<f32>( 3.0, -1.0),
    vec2<f32>(-1.0,  3.0),
  );
  var uv = array<vec2<f32>, 3>(
    vec2<f32>(0.0, 1.0),
    vec2<f32>(2.0, 1.0),
    vec2<f32>(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4<f32>(pos[vi], 0.0, 1.0);
  out.uv = uv[vi];
  return out;
}

@fragment
fn fs(input: VertexOutput) -> @location(0) vec4<f32> {
  return textureSample(srcTexture, srcSampler, input.uv);
}
`;

// Cached resources (created once per device, reused across all textures)
const pipelineCache = new Map<string, GPURenderPipeline>();
let shaderModule: GPUShaderModule | null = null;
let linearSampler: GPUSampler | null = null;
let bindGroupLayout: GPUBindGroupLayout | null = null;
let _cachedDevice: GPUDevice | null = null;

/** Clear cached mipmap generation resources. Must be called when a GPU device is destroyed. */
function clearMipmapCache(): void {
    pipelineCache.clear();
    shaderModule = null;
    linearSampler = null;
    bindGroupLayout = null;
    _cachedDevice = null;
}

function ensureResources(device: GPUDevice): void {
    if (device !== _cachedDevice) {
        clearMipmapCache();
        _cachedDevice = device;
    }
    if (!shaderModule) {
        shaderModule = device.createShaderModule({ code: BLIT_SHADER });
    }
    if (!linearSampler) {
        linearSampler = getOrCreateSampler(device, { magFilter: "linear", minFilter: "linear" });
    }
    if (!bindGroupLayout) {
        bindGroupLayout = device.createBindGroupLayout({
            entries: [
                { binding: 0, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: "float" } },
                { binding: 1, visibility: GPUShaderStage.FRAGMENT, sampler: {} },
            ],
        });
    }
}

function getPipeline(device: GPUDevice, format: GPUTextureFormat): GPURenderPipeline {
    ensureResources(device);
    let pipeline = pipelineCache.get(format);
    if (!pipeline) {
        pipeline = device.createRenderPipeline({
            layout: device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout!] }),
            vertex: { module: shaderModule!, entryPoint: "vs" },
            fragment: {
                module: shaderModule!,
                entryPoint: "fs",
                targets: [{ format }],
            },
            primitive: { topology: "triangle-list" },
        });
        pipelineCache.set(format, pipeline);
    }
    return pipeline;
}

/**
 * Generate a full mip chain for a 2D texture via GPU blit passes.
 * Mip 0 must already contain data. Each subsequent mip is generated by
 * sampling the previous mip with bilinear filtering.
 *
 * For sRGB formats, filtering happens in linear space (GPU handles conversion).
 * The texture must have TEXTURE_BINDING and RENDER_ATTACHMENT usage flags.
 */
export function generateMipmaps(device: GPUDevice, texture: GPUTexture): void {
    if (texture.mipLevelCount <= 1) {
        return;
    }

    const pipeline = getPipeline(device, texture.format);
    const encoder = device.createCommandEncoder();

    for (let mip = 1; mip < texture.mipLevelCount; mip++) {
        const srcView = texture.createView({
            baseMipLevel: mip - 1,
            mipLevelCount: 1,
        });
        const dstView = texture.createView({
            baseMipLevel: mip,
            mipLevelCount: 1,
        });

        const bindGroup = device.createBindGroup({
            layout: bindGroupLayout!,
            entries: [
                { binding: 0, resource: srcView },
                { binding: 1, resource: linearSampler! },
            ],
        });

        const pass = encoder.beginRenderPass({
            colorAttachments: [
                {
                    view: dstView,
                    loadOp: "clear",
                    storeOp: "store",
                    clearValue: { r: 0, g: 0, b: 0, a: 0 },
                },
            ],
        });

        pass.setPipeline(pipeline);
        pass.setBindGroup(0, bindGroup);
        pass.draw(3);
        pass.end();
    }

    device.queue.submit([encoder.finish()]);
}

/** Calculate full mip chain count for a given width/height. */
export function mipLevelCount(width: number, height: number): number {
    return Math.floor(Math.log2(Math.max(width, height))) + 1;
}
